spring:
  datasource:
    url: jdbc:mysql://localhost:3308/sfg_dev
    username: sfg_dev_user
    password: password
  jpa:
    hibernate:
      ddl-auto: validate  # You don't want Hibernate doing DDL changes
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
    # The following code uses Hibernate to generate schema for MySQL.
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              # Creates a .sql in the project root folder that contains SQL queries
#              create-target: sfg_database_create.sql